# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: financial_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'financial_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66inancial_data.proto\x12\tfinancial\"\x1e\n\x0cStockRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"F\n\x12StockPriceResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"$\n\x11\x42\x61tchStockRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"p\n\x12\x42\x61tchStockResponse\x12-\n\x06prices\x18\x01 \x03(\x0b\x32\x1d.financial.StockPriceResponse\x12\x15\n\rsuccess_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x66\x61iled_count\x18\x03 \x01(\x05\x32\xae\x01\n\x14\x46inancialDataService\x12G\n\rGetStockPrice\x12\x17.financial.StockRequest\x1a\x1d.financial.StockPriceResponse\x12M\n\x0eGetBatchPrices\x12\x1c.financial.BatchStockRequest\x1a\x1d.financial.BatchStockResponseB*\n\x12\x63om.finsight.protoB\x12\x46inancialDataProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'financial_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.finsight.protoB\022FinancialDataProtoP\001'
  _globals['_STOCKREQUEST']._serialized_start=35
  _globals['_STOCKREQUEST']._serialized_end=65
  _globals['_STOCKPRICERESPONSE']._serialized_start=67
  _globals['_STOCKPRICERESPONSE']._serialized_end=137
  _globals['_BATCHSTOCKREQUEST']._serialized_start=139
  _globals['_BATCHSTOCKREQUEST']._serialized_end=175
  _globals['_BATCHSTOCKRESPONSE']._serialized_start=177
  _globals['_BATCHSTOCKRESPONSE']._serialized_end=289
  _globals['_FINANCIALDATASERVICE']._serialized_start=292
  _globals['_FINANCIALDATASERVICE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
