# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import financial_data_pb2 as financial__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in financial_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinancialDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockPrice = channel.unary_unary(
                '/financial.FinancialDataService/GetStockPrice',
                request_serializer=financial__data__pb2.StockRequest.SerializeToString,
                response_deserializer=financial__data__pb2.StockPriceResponse.FromString,
                _registered_method=True)
        self.GetBatchPrices = channel.unary_unary(
                '/financial.FinancialDataService/GetBatchPrices',
                request_serializer=financial__data__pb2.BatchStockRequest.SerializeToString,
                response_deserializer=financial__data__pb2.BatchStockResponse.FromString,
                _registered_method=True)


class FinancialDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStockPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinancialDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockPrice,
                    request_deserializer=financial__data__pb2.StockRequest.FromString,
                    response_serializer=financial__data__pb2.StockPriceResponse.SerializeToString,
            ),
            'GetBatchPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchPrices,
                    request_deserializer=financial__data__pb2.BatchStockRequest.FromString,
                    response_serializer=financial__data__pb2.BatchStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'financial.FinancialDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('financial.FinancialDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinancialDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStockPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financial.FinancialDataService/GetStockPrice',
            financial__data__pb2.StockRequest.SerializeToString,
            financial__data__pb2.StockPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financial.FinancialDataService/GetBatchPrices',
            financial__data__pb2.BatchStockRequest.SerializeToString,
            financial__data__pb2.BatchStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
